### Schema

USE a9tj0ozkj9w9uqcd;

CREATE TABLE tacos
(
	id INT NOT NULL AUTO_INCREMENT,
	taco_name VARCHAR(255) NOT NULL,
	devoured BOOLEAN NOT NULL DEFAULT 0,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);