### Schema
CREATE DATABASE tacos_db;
USE tacos_db;

CREATE TABLE tacos
(
	id INT NOT NULL AUTO_INCREMENT,
	taco_name VARCHAR(255) NOT NULL,
	devoured BOOLEAN NOT NULL DEFAULT 0,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);